version: '3.8'

services:
  LogAnalyzer:
    image: edino/docker-loganalyzer:arm64
    container_name: LogAnalyzer
    restart: always
    ports:
      - "80:80"
    volumes:
      - /docker/data:/data
    networks:
      my_network:
        ipv4_address: 192.168.1.2  # Replace with your desired container IP
    healthcheck:
      test: ["CMD", "/health_check.sh"]
      interval: 4m
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

networks:
  my_network:
