name: ci

on:
  push:
    # branches:
    #   - 'master'
    tags:
      - '*.*.*'

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: build
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/386, linux/amd64
        tags: |
          ${{ github.repository_owner }}/loganalyzer:${{ github.ref_name }}
          ${{ github.repository_owner }}/loganalyzer:latest
        build_args: loganalyzer_ver=${{ github.ref_name }}
